use_frameworks!
target 'A00CppInitMeasureExample' do
  # 统计项目中 +load 方法及耗时、统计启动main之后函数调用耗时，需要设置为动态库
  # 默认 Framework 模式
#  pod 'A00CppInitMeasure', :path => '../'
  
  # 使用 Source 模式
  pod 'A00CppInitMeasure/Source', :path => '../'
end
